import Head from "next/head";
import type { AppProps } from "next/app";
import { CssBaseline, MuiThemeProvider } from "@material-ui/core";
import { Component } from "react";

import { theme } from "../theme";
import { Header } from "../components/Header";
import { wrapper } from "../redux/store";
import { setUserData } from "../redux/slices/user";
import { Api } from "../utils/api";

import "macro-css";
import "../styles/globals.scss";


function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>🌀R-magazine</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="../public/favicon.ico"/>
				<link rel="preconnect" href="https://fonts.googleapis.com"/>
				<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=""/>
				<link
					href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,400;1,500;1,700;1,900&display=swap"
					rel="stylesheet"/>
			</Head>
			<MuiThemeProvider theme={theme}>
				<CssBaseline/>
				<Header/>
				<Component {...pageProps} />
			</MuiThemeProvider>
		</>
	);
}

App.getInitialProps = wrapper.getInitialAppProps((store) => async ({ ctx, Component }) => {
	try {
		const userData = await Api(ctx).user.getMe();
		store.dispatch(setUserData(userData));
	} catch (err: any) {
		if (ctx.asPath === "/write") {
			ctx.res?.writeHead(302, {
				Location: "/403",
			});
			ctx.res?.end();
		}
		console.log("❌ERROR: ", err);
	}
	return {
		pageProps: Component.getInitialProps ? await Component.getInitialProps({ ...ctx, store }) : {},
	};
});

export default wrapper.withRedux(App);
